export default {
  SET_APP_LOADED: 'SET_APP_LOADED',
  SET_USER: 'SET_USER',
  SET_SELECTED_FOLDER: 'SET_SELECTED_FOLDER',
  SET_SELECTED_NOTE: 'SET_SELECTED_NOTE',
  SHOW_POPUP: 'SHOW_POPUP',
  CLOSE_POPUP: 'CLOSE_POPUP',
  SHOW_NOTE_EDITOR: 'SHOW_NOTE_EDITOR',
  HIDE_NOTE_EDITOR: 'HIDE_NOTE_EDITOR',
  SET_TAGS_VALUE: 'SET_TAGS_VALUE',
  SHOW_TAGS_INPUT: 'SHOW_TAGS_INPUT',
  HIDE_TAGS_INPUT: 'HIDE_TAGS_INPUT',
};
