export default {
  SET_APP_LOADED: 'SET_APP_LOADED',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SET_SELECTED_FOLDER: 'SET_SELECTED_FOLDER',
  SET_SELECTED_NOTE: 'SET_SELECTED_NOTE',
  SET_ALL_NOTES: 'SET_ALL_NOTES',
  SHOW_NOTE_EDITOR: 'SHOW_NOTE_EDITOR',
  HIDE_NOTE_EDITOR: 'HIDE_NOTE_EDITOR',
};
