export default {
  SET_APP_LOADED: 'SET_APP_LOADED',
  SET_USER: 'SET_USER',
  SET_SELECTED_FOLDER: 'SET_SELECTED_FOLDER',
  SET_SELECTED_NOTE: 'SET_SELECTED_NOTE',
  SHOW_NOTE_EDITOR: 'SHOW_NOTE_EDITOR',
  HIDE_NOTE_EDITOR: 'HIDE_NOTE_EDITOR',
};
